openearth/delft3d-gt-ui

app/index.html, app/styles/website.scss
Added reference to website.css
=> Added reference to website.css

.travis.yml, gulpfile.babel.js, package.json
Generate test output for teamcity.
=> testing for teamcity (use npm test or  gulp test)

app/scripts/main.js
Baseurl empty by default.
TODO: see if we can use  https://www.browsersync.io/docs/options/ to proxy.
=> default to no base

app/scripts/main.js, app/scripts/models.js, app/scripts/ui.js
=> fix braces

app/styles/main.scss, app/templates/model-details.html
Fix the scsslint errors. Please consider avoiding:
- too deep [nesting](http://sass-lang.com/guide#topic-3) (table tbody td etc... do you have td's outside of tables?)
- [styling on id ](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#idselector)
- [qualifying elements](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#qualifyingelement) 
- too [deep selectors](https://smacss.com/book/applicability)
=> cleanup styles (lint and consistent colors)

app/scripts/app.js, app/scripts/components/modeldetails.js, app/scripts/components/modellist.js, app/scripts/data/message-scene-changestate.js, app/scripts/data/message-scene-create.js, app/scripts/data/message-scene-delete.js, app/scripts/data/message-scene-list.js, app/scripts/models.js, app/templates/model-details.html, package.json, test/spec/test.js
Modeldetails now have animated images coming from incoming data
=> Modeldetails now have animated images coming from incoming data

app/scripts/app.js, app/scripts/components/modeldetails.js, app/scripts/main.js, app/scripts/models.js, app/scripts/ui.js, gulpfile.babel.js
Removed some code and old comments, made working dir source of the logfile.
=> Some code cleanup

app/scripts/components/home.js, app/scripts/components/modeldetails.js, app/scripts/inputvalidation.js, app/scripts/models.js, app/styles/main.scss, app/templates/home.html, app/templates/list-running-models.html, app/templates/model-details.html, gulpfile.babel.js
- sidebar collapse is fixed
- workingdir became "fileurl"
- "no models running" message is now inside table (looks a bit better)
=> Ui detailview fix

app/scripts/data/message-scene-changestate.js, app/scripts/data/message-scene-create.js, app/scripts/data/message-scene-delete.js, package.json, test/spec/nock-example.js, test/spec/test.js
Make sure to add `"Access-Control-Allow-Origin": "*"` to `defaultReplyHeaders` when using a nock server.
=> Feature sprint03 robin nock test

app/scripts/components/scenariobuilder.js, app/styles/main.scss, app/templates/scenario-builder.html, gulpfile.babel.js
For:
https://issuetracker.deltares.nl/browse/DELFT3DGT-97
Data is now send to server. Templates are selectable.
Pending issue: Ordering of fields in the template
=> Feature sprint03 almar templates from url

gulpfile.babel.js
The teamcity gulp task did some duplicate work which caused the error.
=> Feature sprint03 Robin teamcity prefilter fix

app/scripts/components/modeldetails.js, app/scripts/components/scenariobuilder.js, app/scripts/models.js, app/scripts/templates.js, app/templates/scenario-builder.html, test/spec/test.js
Temlate data was not fetched properly
move to template.js
=> fix scenario builder

gulpfile.babel.js, package.json
Now only `--apiServer <value>` supported.
Other arguments can be added in `processOptionalArguments`
=> Added ability to add optional arguments to gulp

app/index.html, app/scripts/app.js, app/scripts/components/findercolumns.js, app/scripts/components/modeldetails.js, app/scripts/components/modellist.js, app/scripts/components/scenariolist.js, app/scripts/scenarios.js, app/templates/finder-columns.html, app/templates/home.html, app/templates/model-list.html, app/templates/scenario-list.html, test/spec/test.js
Three column layout. Optional attribute filter="scenarios" used to keep a default list of all running models.
=> Feature sprint03 fedor finder view

app/templates/model-list.html
=> [] == false, but ![] is not true

app/scripts/components/modeldetails.js, app/scripts/components/modellist.js, app/styles/main.scss
Fixes vertical scrolling and routing after delete
=> Bugfix sprint03 fedor tweaks

app/index.html, app/scripts/components/imageanimation.js, app/scripts/components/modeldetails.js, app/styles/main.scss, app/templates/finder-columns.html, app/templates/imageanimation.html, app/templates/model-details.html, test/spec/test.js
Added imageanimation component.
Has an error in the test, will fix this later.
=> Committing this ,but it has an a Mocha error

app/index.html, app/scripts/components/findercolumns.js, app/scripts/components/imageanimation.js, app/scripts/components/scenariobuilder.js, app/scripts/models.js, app/scripts/scenarios.js, app/styles/main.scss, app/templates/finder-columns.html, app/templates/imageanimation.html, app/templates/model-details.html, app/templates/scenario-builder.html, test/spec/test.js
- Log output has max height and not rounded borders anymore
- Centered image type selection
- Display which image type is active
- Added some description of the images
- Added frame counter
- Added no cache to models/scenario list (could not test if this works)
- Added variable to submitted scenario so it should show up in the runs
list (could not test)
- Removed one test as it keeps giving errors for some strange reason,
while all seems to look OK client side.
=> Various UI fixes

app/scripts/components/modeldetails.js, app/templates/model-details.html
Added progressbar to the detail view
=> Added progressbar to the detail view

app/styles/main.scss, app/templates/scenario-builder.html
improving layout of scenariobuilder
=> improving layout of scenariobuilder

app/scripts/components/modeldetails.js, app/templates/model-details.html
=> Logfile is not loaded automatically, only upon request

app/index.html, app/login.html, app/styles/main.scss, app/templates/model-list.html
Progress not yet, see comment @ JIRaA
https://issuetracker.deltares.nl/browse/DELFT3DGT-200
=> Showing badge in run list

package.json, test/spec/test.js
The more elegant way to check if a method is called is to use a spy.
=> Using a spy to assert that method is called.

app/scripts/components/searchdetails.js, app/templates/search-columns.html, app/templates/search-details.html
=> Search api

app/scripts/components/modeldetails.js, app/scripts/components/userdetails.js, app/scripts/models.js, app/templates/model-details.html, test/spec/test.js
Added export button to simulation controls. It only calls the correct url now.
=> Export button

app/templates/scenario-builder.html
Added clear error descriptions: empty field, min, max, no number
=> Clear descriptions

app/scripts/components/modeldetails.js, app/scripts/models.js, app/templates/model-details.html, test/spec/test.js
Changed publish control button form calls to ajax calls
=> Publish controls ajax calls

app/scripts/components/scenariobuilder.js, app/templates/scenario-builder.html
Fixed infinite loop for selectTemplate by remembering the last selected template
=> Multiple templates (fixed now)

app/templates/scenario-builder.html
- Fixed wrong error for non-numeric fields
- Added clear messages for tagsinput field
=> Descriptions fix

app/templates/model-details.html
AS requested by Andreas
https://issuetracker.deltares.nl/browse/DELFT3DGT-215
=> Change "vary" to multiple runs

app/scripts/components/scenariobuilder.js, app/styles/main.scss, app/templates/scenario-builder.html
styling (move later to a custom style in io)
=> fix styles

app/scripts/components/modeldetails.js, app/styles/main.scss, app/templates/model-details.html, test/spec/test.js
- Current publish level is visible in the details and is highlighted when changed.
- lower level buttons disabled
- confirmation dialog
- buttons disabled like start and export
- start/etc buttons disabled when published
=> Feature sprint04 robin advanced publish buttons

app/scripts/app.js, app/templates/finder-columns.html, app/templates/imageanimation.html, app/templates/model-details.html
- Fixed the caching of URL's by setting the ajax cache settings global
to false
- Changed a few templates (removed some spaces, adding closing tags,
indentation) and made Gulp work again by replacing "@click" to
"v-on:click="
=> AJAX cache fix & template fix

app/scripts/components/scenariobuilder.js, app/styles/main.scss, app/templates/model-details.html
See build https://travis-ci.org/openearth/delft3d-gt-ui/builds/136410328
=> Parameter table update

app/styles/main.scss, app/templates/model-details.html
As mentioned here
https://issuetracker.deltares.nl/browse/DELFT3DGT-249
=> Fix for download text

app/scripts/components/findercolumns.js, app/scripts/components/scenariobuilder.js, test/spec/test.js
One issue remaining, name is both a variable and a scenario property.
=> Fix clone parameters

app/scripts/components/searchlist.js
Also the search details. Uncommented the old code for that, as I think
it should work just fine(!)?
=> Automatically update search results over time

app/templates/search-details.html
See: http://getbootstrap.com/components/#input-groups-buttons
=> fix button between different browsers

app/api/v1/templates/index.html
=> template update

app/templates/scenario-builder.html
I should have made it smaller....
=> id removed

app/templates/model-control-menu.html
Fixes issue #456 were models are deleted on opening page
=> call functions on click instead of on definition of attribute click

app/index.html, app/templates/model-control-menu.html
=> move button to other place

app/templates/model-details.html
Format the buttons with disabled class if disabled.
=> Buttons disabled

app/scripts/components/scenariobuilder.js
=> fix parsing logic bug

bower.json
Point to commit of tagged version that contains the real code. Other option is to switch to npm, but I like to keep browser packages and client packages separate.
=> Vue validator maintainer added fake code to repository

app/scripts/components/searchdetails.js
Please read the JIRA issue though...
https://issuetracker.deltares.nl/browse/DELFT3DGT-544
=> fixes text field not working.

app/templates/model-control-menu.html
=> make menu look like a dropdown menu

app/scripts/components/scenariobuilder.js, app/scripts/components/searchdetails.js, app/templates/scenario-builder.html, app/templates/scenario-card.html
Solves DELFT3DGT-549, DELFT3DGT-550
=> Firefox bugs

app/scripts/components/scenariocard.js, app/styles/main.scss, app/templates/model-card.html, app/templates/scenario-card.html, app/templates/search-columns.html
Make some room by reducing the padding and use regular checkbox. Note the extra effort to set the indeterminate state of an input, which can only be set using javascript. 
See https://css-tricks.com/indeterminate-checkboxes/ for details. Although the input is referred to as the "tri-state" input it actually has 4 different states, based on 2 properties (indeterminate true/false and checked true/false). 
The select icon is removed if noPrivateModels are available. 
DELFT3DGT-579, DELFT3DGT-560
=> Toggle and scenario card formatting

app/index.html, app/scripts/components/scenariobuilder.js, app/scripts/components/searchdetails.js, app/scripts/store.js, app/templates/search-columns.html
=> Feature sprint07 almar show error connection lost

app/scripts/components/modeldetails.js, app/scripts/components/searchdetails.js, app/scripts/store.js, app/templates/model-details.html, app/templates/search-details.html
=> master: hotfix-sprint10-tijn-postprocess-units

app/scripts/store.js, bower.json, gulpfile.babel.js, package-lock.json, package.json
=> Update some packages
